spring:
  redis:
    database: 0
    password: abc@123     # 密码（默认为空）
    sentinel:
      master: mymaster
      nodes: 192.168.13.16:26379,192.168.2.172:26379,192.168.12.175:26379
    timeout: 12000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 3000    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 3000      # 连接池中的最大空闲连接
        min-idle: 0         # 连接池中的最小空闲连接

