server:
  port: 8090
spring:
  application:
    name: redis-demo
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

logging:
  config: config/logback-spring.xml
  level:
    com.com.example: debug
    org.springframework: debug



